apiVersion: 1

prune: true

datasources:
  - name: Evalflow Prometheus
    uid: evalflow-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
